return {
  "nvim-treesitter/nvim-treesitter",
  branch = "master",  -- will be changed to main in future
  lazy = false,
  build = ":TSUpdate",
  main = "nvim-treesitter.configs",
  opts = {
    ensure_installed = {
      "python",
      "jinja",
      "rust",
      "hcl",
      "typescript",
      "javascript",
      "html",
      "css",
      "graphql",
      "proto",
      "swift",
      "kotlin",
      "ruby",
      "go",
      "c",
      "cpp",
      "lua",
      "vim",
      "vimdoc",
      "json",
      "json5",
      "yaml",
      "toml",
      "query",
      "markdown",
      "markdown_inline",
      "rst",
      "bash",
      "csv",
      "diff",
      "dockerfile",
      "helm",
      "editorconfig",
      "git_config",
      "git_rebase",
      "gitcommit",
      "gitignore",
    },
    highlight = {
      enable = true,
    },
    indent = {
      enable = true,
    },
  },
}
